### ISSUE TITLE
compilation failed

### ISSUE THREAD

**Issue by lmanchon** [smarco/gem3-mapper#4]
--Hi,

some problem at compilation step in source file:

gcc -O2 -DNDEBUG -I../../../include -c match_align_normalize.c -o ../../../build/match_align_normalize.o
match_align_normalize.c: In function ‘match_align_normalize_cigar’:
match_align_normalize.c:108: error: unknown field ‘length’ specified in initializer
match_align_normalize.c:109: error: unknown field ‘length’ specified in initializer

thank you --

**Comment by smarco** [comment]
Hi,

It's weird because as far as I can tell we never compile using -O2 option.
Can you please try again to clone the repository and compile from scratch?
If you still get this error, please send me the command line used and your
system specs so we can solve your problem.

Thanks for the report.
Cheers,

**Comment by lmanchon** [comment]
ok, good i have loaded gcc-4.9.1 and now it compiled fine.
The error was due to the fact that some old compilers version don't accept the -Ofast option. I have changed it to a more general -O2 option and then compile with gcc-4.6.2, some object files are compiled but others not. 
Laurent --

**Comment by smarco** [comment]
Ok, great. We will add a minimum requirements list.

Thanks,

**Comment by lmanchon** [comment]
Sorry i have a question about the .csv file i need to use, i have fastq.gz files and i don't understand what 'flowcell,lane,index' means, can you give me an explicit example please ?
thank you --

**Comment by smarco** [comment]
In principle, there is no need to use any cvs file in order tu perform
regular sequence mapping. Just provide the mapper with the fastq.gz file.
README should give a brief example of this.

Let me know.

El 19 ene. 2018 12:30 p. m., "lmanchon" <notifications@github.com> escribió:

Sorry i have a question about the .csv file i need to use, i have fastq.gz
files and i don't understand what 'flowcell,lane,index' means, can you give
me an explicit example please ?
thank you --

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/smarco/gem3-mapper/issues/4#issuecomment-358940570>,
or mute
the thread

**Comment by lmanchon** [comment]
i thought about gemBS: http://statgen.cnag.cat/GEMBS/UserGuide/_build/html/pipelineSteps.html

**Comment by smarco** [comment]
Ah, ok. Bear in mind that the framework GEMBS is another project, despite
using GEM3 to perform the mapping.

The CVS file is used by GEMBS to include the proper metadata information
into the SAM/BAM files generated (i.e. sample,library,flowcell,lane,index).
The GEMBS documentation gives an example:

tissue_1,lib_1,flowcell_A,1,1tissue_1,lib_1,flowcell_A,2,1tissue_1,lib_1,flowcell_A,3,1tissue_2,lib_2,flowcell_A,4,1tissue_2,lib_2,flowcell_A,5,1tissue_3,lib_1,flowcell_B,1,1


Let me know if that helps.
Cheers,

El 19 ene. 2018 12:38 p. m., "lmanchon" <notifications@github.com> escribió:

i thought about gemBS: http://statgen.cnag.cat/GEMBS/
UserGuide/_build/html/pipelineSteps.html

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/smarco/gem3-mapper/issues/4#issuecomment-358942373>,
or mute
the thread

**Comment by lmanchon** [comment]
ok, thank you so much.
